version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 22
  pre_build:
    commands:
      - echo Logging into AWS CodePipeline
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 282865065290.dkr.ecr.us-east-1.amazonaws.com/cursoarquitectura10
  build:
    commands:
      - echo Build started at `date`
      - echo Building the docker image
      - cd app-courses
      - aws s3 cp s3://cursoarquitectura10/$ENVIRONMENT/.env .env
      - docker build -t cursoarquitectura10 .
      - docker tag cursoarquitectura10 282865065290.dkr.ecr.us-east-1.amazonaws.com/cursoarquitectura10
    post_build:
      commands:
        - docker push 282865065290.dkr.ecr.us-east-1.amazonaws.com/cursoarquitectura10
artifacts:
  files:
    - "Dockerrun.aws.json"